manifests/install.pp
Ensure install dir and its contents belong to keycloak user
=> Fix ownership of install dir

manifests/client_template.pp
https://github.com/keycloak/keycloak/blob/master/saml-core/src/main/java/org/keycloak/saml/processing/core/saml/v2/constants/X500SAMLProfileConstants.java
=> Fix SAML username protocol mapper to match keycloak code

lib/puppet/provider/keycloak_ldap_user_provider/kcadm.rb, lib/puppet/type/keycloak_ldap_user_provider.rb, spec/acceptance/3_ldap_spec.rb, spec/unit/puppet/type/keycloak_ldap_user_provider_spec.rb
=> Add search_scope and custom_user_search_filter properties to keycloak_ldap_user_provider type

README.md, lib/puppet/provider/keycloak_sssd_user_provider/kcadm.rb, lib/puppet/type/keycloak_sssd_user_provider.rb, manifests/init.pp, manifests/params.pp, manifests/sssd.pp, spec/acceptance/3_sssd_spec.rb, spec/fixtures/unit/puppet/provider/keycloak_sssd_user_provider/kcadm/get-master.out, spec/fixtures/unit/puppet/provider/keycloak_sssd_user_provider/kcadm/get-test.out, spec/unit/puppet/provider/keycloak_sssd_user_provider/kcadm_spec.rb, spec/unit/puppet/type/keycloak_sssd_user_provider_spec.rb
Added class parameters:
* with_sssd_support
* libunix_dbus_java_source
* install_libunix_dbus_java_build_dependencies
* libunix_dbus_java_build_dependencies
* libunix_dbus_java_libdir
* jna_package_name
* manage_sssd_config
* sssd_ifp_user_attributes
* restart_sssd
Added keycloak_sssd_user_provider type/provider
=> Support SSSD User Provider

lib/puppet/provider/keycloak_client/kcadm.rb, lib/puppet/provider/keycloak_client_protocol_mapper/kcadm.rb, lib/puppet/provider/keycloak_client_scope/kcadm.rb, lib/puppet/provider/keycloak_ldap_user_provider/kcadm.rb, lib/puppet/provider/keycloak_protocol_mapper/kcadm.rb, lib/puppet/provider/keycloak_sssd_user_provider/kcadm.rb, lib/puppet/type/keycloak_client_protocol_mapper.rb, lib/puppet/type/keycloak_protocol_mapper.rb, spec/unit/puppet/provider/keycloak_client/kcadm_spec.rb, spec/unit/puppet/provider/keycloak_client_protocol_mapper/kcadm_spec.rb, spec/unit/puppet/provider/keycloak_client_scope/kcadm_spec.rb, spec/unit/puppet/provider/keycloak_ldap_user_provider/kcadm_spec.rb, spec/unit/puppet/provider/keycloak_protocol_mapper/kcadm_spec.rb, spec/unit/puppet/provider/keycloak_sssd_user_provider/kcadm_spec.rb, spec/unit/puppet/type/keycloak_client_protocol_mapper_spec.rb, spec/unit/puppet/type/keycloak_protocol_mapper_spec.rb
* Improve id handling for keycloak_client_protocol_mapper
* Improve id handling for keycloak_protocol_mapper
* Make flush and destroy id handling consistent across all types that use id
=> Better ID handling

REFERENCE.md, manifests/init.pp, manifests/params.pp, templates/keycloak.service.erb
Fixes https://github.com/treydock/puppet-module-keycloak/issues/49
=> JAVA_OPTS via systemd unit Environment variable

.fixtures.yml, manifests/init.pp, metadata.json, templates/keycloak.service.erb
This is useful for example when there is a reverse proxy is in front of Keycloak
=> Enable defining bind address for the Keycloak systemd service

lib/puppet/type/keycloak_client.rb, spec/unit/puppet/type/keycloak_client_spec.rb
- service_accounts_enabled (serviceAccountsEnabled)
- standard_flow_enabled (standardFlowEnabled)
- implicit_flow_enabled (implicitFlowEnabled)
=> Add support for more client switches

manifests/config.pp, manifests/init.pp, spec/classes/init_spec.rb, spec/spec_helper_local.rb, templates/profile.properties.erb
=> Add option to enable tech preview features

lib/puppet/type/keycloak_realm.rb, spec/unit/puppet/type/keycloak_realm_spec.rb
This brings with it unit testing of integer-valued properties
=> Add two new realm properties

manifests/config.pp, manifests/init.pp, spec/classes/init_spec.rb
Closes https://github.com/treydock/puppet-module-keycloak/issues/141
=> Concat custom code fragment to config.cli

lib/puppet/provider/keycloak_client_protocol_mapper/kcadm.rb, lib/puppet/type/keycloak_client_protocol_mapper.rb
=> Support oidc-usermodel-client-role-mapper type in client protocol mapper

lib/puppet/type/keycloak_realm.rb, spec/unit/puppet/type/keycloak_realm_spec.rb
This adds suppor for ssoSessionIdleTimeoutRememberMe and
ssoSessionMaxLifespanRememberMe.
=> Support realm remember_me parameters

manifests/sssd.pp
=> Fix puppet-lint warning

manifests/config.pp, templates/config.cli/01-https-proxy.epp, templates/config.cli/11-domain.epp
Be explicit about using ha sockets with domain mode
=> Domain mode sockets

.github/workflows/ci.yaml, .sync.yml, Gemfile, README.md, metadata.json
=> Support Keycloak 13.x

manifests/config.pp
Signed-off-by: Kibahop <petri.lammi@puppeteers.net>
=> Fix and tune mangement interface definitions for both master and slave

REFERENCE.md, lib/puppet/type/keycloak_realm.rb, spec/acceptance/2_realm_spec.rb, spec/unit/puppet/type/keycloak_realm_spec.rb
keycloak_realm to accept user_managed_access_allowed
=> Add feature `user_managed_access_allowed` property

manifests/freeipa_user_provider.pp, spec/defines/freeipa_user_provider_spec.rb
=> Add id parameter to keycloak::freeipa_user_provider

lib/puppet/provider/keycloak_flow/kcadm.rb
=> Fix to set description on keycloak_flow when not top_level flow

lib/puppet/provider/keycloak_flow/kcadm.rb, spec/acceptance/9_flow_spec.rb
=> Further fix to set description on keycloak_flow when not top_level flow

lib/puppet/provider/keycloak_api.rb, lib/puppet/provider/keycloak_realm/kcadm.rb, lib/puppet/type/keycloak_realm.rb, spec/acceptance/2_realm_spec.rb, spec/unit/puppet/type/keycloak_realm_spec.rb
Add `ssl_required` and `edit_username_allowed` properties
Add `custom_properties` property
Fixes #222
=> Add Realm properties and allow custom properties

templates/config.cli/02-datasource.epp
=> Quota datasource username and password

.fixtures.yml, .github/workflows/ci.yaml, .rubocop.yml, .sync.yml, Gemfile, README.md, metadata.json, spec/acceptance/nodesets/debian-11.yml, spec/acceptance/nodesets/rocky-8.yml
=> Support Debian 11

metadata.json
This PR adds support for the postgresql module 8 (< 9.0.0)
=> Allow postgresql < 9.0.0

types/configs.pp
This option is loaded relative to conf/
=> Use a regular string for cache-config-file option

manifests/init.pp, spec/classes/init_spec.rb, templates/keycloak.service.erb
=> Remove --auto-build from start command on Keycloak 19+

templates/kcadm-wrapper.sh.erb
=> Wrap kcadm-wrapper arguments in quotes

lib/puppet/provider/keycloak_api.rb, spec/acceptance/2_realm_spec.rb
=> Allow keycloak.v2 theme to be used

README.md, manifests/init.pp, spec/classes/init_spec.rb
=> Allow hostname setting to not use default value

lib/puppet/provider/keycloak_conn_validator/puppet_https.rb, lib/puppet/type/keycloak_conn_validator.rb, lib/puppet/util/keycloak_validator.rb, manifests/init.pp
=> Use http_relative_path with keycloak_conn_validator

lib/puppet/type/keycloak_ldap_user_provider.rb, spec/acceptance/3_ldap_spec.rb, spec/unit/puppet/type/keycloak_ldap_user_provider_spec.rb
=> Add cache_policy property to keycloal_ldap_user_provider

data/os/Debian.yaml, data/os/Debian/11.yaml, manifests/init.pp
=> Default java_declare_method to class for Debian and Ubuntu

manifests/init.pp, spec/classes/init_spec.rb, templates/keycloak.service.erb
=> Set JAVA_HOME environment variable for Keycloak service

manifests/init.pp, spec/classes/init_spec.rb
=> Do not reassign $hostname variable when http_enabled=false

lib/puppet/provider/keycloak_client_protocol_mapper/kcadm.rb, lib/puppet/type/keycloak_client_protocol_mapper.rb, spec/acceptance/7_client_protocol_mapper_spec.rb, spec/unit/puppet/type/keycloak_client_protocol_mapper_spec.rb
* usermodel_client_role_mapping_client_id
* multivalued
Fixes #234
=> Add properties to keycloak_client_protocol_mapper

lib/puppet/provider/keycloak_ldap_user_provider/kcadm.rb
Fix: https://github.com/treydock/puppet-module-keycloak/issues/317
=> Fix ldap user provider parent_id lookup

manifests/init.pp, manifests/resources.pp
We have additional updates, please, consider merging.
In this PR we add role mapping configuration.
Thank you.
Regards,
Robert.
=> Add role mappings
