manifests/datasource/mysql.pp

At least on Debian 9 with puppetlabs/mysql 5.2.1, /usr/share/java/mysql-connector-java.jar is a local symlink to mysql-connector-java-5.1.42.jar, so if you copy it verbatim to another location it ends broken.
I think changing the policy from copying to symlinking has no side effects and makes it run smooth.

Symlink instead of copy mysql connector. puppetlabs/mysql 5 compatibility

---

lib/puppet/provider/keycloak_protocol_mapper/kcadm.rb
lib/puppet/type/keycloak_protocol_mapper.rb
manifests/client_template.pp
spec/acceptance/4_client_template_spec.rb
spec/acceptance/6_protocol_mapper_spec.rb
spec/unit/puppet/type/keycloak_protocol_mapper_spec.rb

Add several properties to keycloak_protocol_mapper that are specific to SAML clients.
Add the builtin SAML client protocol mappers to keycloak::client_template when protocol=saml

Add SAML support to keycloak_protocol_mapper and keycloak::client_template

---

lib/puppet/provider/keycloak_protocol_mapper/kcadm.rb
lib/puppet/type/keycloak_protocol_mapper.rb
manifests/client_template.pp
spec/unit/puppet/type/keycloak_protocol_mapper_spec.rb

A mapping will take place from simple values to the actual values passed to keycloak

Allow keycloak_protocol_mapper attribute_nameformat to be simpler values

---

lib/puppet/type/keycloak_client.rb
lib/puppet/type/keycloak_client_template.rb
lib/puppet/type/keycloak_ldap_mapper.rb
lib/puppet/type/keycloak_ldap_user_provider.rb
lib/puppet/type/keycloak_protocol_mapper.rb

This commit makes the module compatible with `puppet generate types`.
Environment isolation is *really* important for a module where types
are having new parameters added on a regular basis.
See
https://tickets.puppetlabs.com/browse/MODULES-4505?focusedCommentId=418416&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-418416
https://github.com/puppetlabs/puppetlabs-java_ks/pull/169
https://github.com/biemond/biemond-wildfly/pull/227

Fix title patterns that use procs are not supported

---

lib/puppet/type/keycloak_ldap_user_provider.rb
spec/unit/puppet/type/keycloak_ldap_user_provider_spec.rb

Added properties:
* use_kerberos_for_password_authentication
* bind_dn
* bind_credential
Should resolve #23

Support setting auth_type=simple related properties for keycloak_ldap_user_provider type

---

lib/puppet/type/keycloak_protocol_mapper.rb
spec/unit/puppet/type/keycloak_client_spec.rb
spec/unit/puppet/type/keycloak_client_template_spec.rb
spec/unit/puppet/type/keycloak_ldap_mapper_spec.rb
spec/unit/puppet/type/keycloak_ldap_user_provider_spec.rb
spec/unit/puppet/type/keycloak_protocol_mapper_spec.rb
spec/unit/puppet/type/keycloak_realm_spec.rb

keycloak_protocol_mapper type property will default to `saml-user-property-mapper` when `protocol` is `saml`.
Add some extra validations to keycloak_protocol_mapper around `type` and `protocol` combinations

Fix for keycloak_protocol_mapper type property and type unit test improvements

---

Gemfile
lib/puppet/provider/keycloak_ldap_mapper/kcadm.rb
lib/puppet/type/keycloak_ldap_mapper.rb
spec/acceptance/3_ldap_spec.rb
spec/unit/puppet/provider/keycloak_ldap_mapper/kcadm_spec.rb
spec/unit/puppet/type/keycloak_ldap_mapper_spec.rb

* Fix keycloak_ldap_mapper so that write_only only applies when type is full-name-ldap-mapper
* Better id handling for keycloak_ldap_mapper
* Move keycloak_ldap_mapper validations to be handled by the type and not the provider
Should fix issue where changing pre-installed components would fail without `id` specified.  Should fix #44

Fix keycloak_ldap_mapper id handling and write_only property

---

manifests/init.pp
templates/keycloak.service.erb

First, thanks for this great module! We're using the it for setting up a Keycloak instance that uses a custom extension. This extension needs configuring some environment variables, and the best seems to manage them in the `keycloak.service` file.
The pull request adds a parameter for including the `EnvironmentFile` option into the systemd service file, so it makes possible to configure environment variables for the Keycloak service.

Add option for service environment file

---

manifests/init.pp
manifests/install.pp

Ability to control if the module should be control the Linux user for keycloak.

manage user support

---

lib/puppet/provider/keycloak_realm/kcadm.rb
lib/puppet/type/keycloak_realm.rb
spec/acceptance/2_realm_spec.rb
spec/unit/puppet/provider/keycloak_realm/kcadm_spec.rb
spec/unit/puppet/type/keycloak_realm_spec.rb

Added properties to keycloak_realm:
* events_enabled
* events_expiration
* events_listeners
* admin_events_enabled
* admin_events_details_enabled

Support managing realm's events config

---

lib/puppet/provider/keycloak_realm/kcadm.rb
spec/unit/puppet/provider/keycloak_realm/kcadm_spec.rb

All event configs must be specified during updates or some could be lost

Fix handling of events config during updates

---

manifests/init.pp
spec/acceptance/1_class_spec.rb
templates/config.cli.erb
templates/keycloak.service.erb

According to: https://www.keycloak.org/docs/latest/server_installation/index.html#standalone-clustered-boot-script
> You use the same boot scripts to start Keycloak as you do in standalone mode. The difference is that you pass in an additional flag to point to the HA config file
> 
> To boot the server:
> $ .../bin/standalone.sh --server-config=standalone-ha.xml
Those were the only changes needed. About the tests, I would need your help for a more meaningful ones.

Fix #78. Add clustered mode support

---

Vagrantfile
vagrant-common.sh

Provisioning was split into OS-specific and OS-agnostic parts to reduce code
duplication.

Vagrant: add Ubuntu 1804 box

---

manifests/init.pp
templates/keycloak.service.erb

This allows passing arbitrary command-line options as a string to standalone.sh in the systemd unit file.

Enable passing extra options to Keycloak in the systemd unit file

---

manifests/init.pp
manifests/install.pp

Example usage from a profile with a package that installs Keycloak to /opt/keycloak-7.0.0 from an apt (or yum) repository:
```
package { 'keycloak':
ensure => 'present',
before => Class['::keycloak'],
}
class { 'keycloak':
manage_install => false,
version        => '7.0.0',
}
```
Owner and group of the files in the package are assumed _not_ to be correct, for example "root:root". Therefore are recursive chown is done to the install directory. That way the user and group the package sets does not have to be kept in sync with $::keycloak::user and $::keycloak::group in this module.
That said, I can handle the chowning in a package post-install script as well, if that seems more reasonable to you.

Allow managing Keycloak installation from outside this module

---

manifests/init.pp

As discussed here: https://github.com/treydock/puppet-module-keycloak/issues/92
This is the first approach I came up with maybe we can discuss a bit further.
When this gets accepted I might opened a new PR to sort the variables alphabetically :)

Make JDBC xa-datasource-class name configurable

---

.travis.yml
manifests/config.pp
manifests/init.pp
spec/acceptance/1_class_spec.rb
spec/classes/init_spec.rb
templates/keycloak.service.erb

Fixes #104
No longer set `JAVA_OPTS` inside the systemd unit file. Instead append to `JAVA_OPTS` inside `bin/standalone.conf`.
Add `java_opts_append` parameter
BREAKING:
* Rename `service_java_opts` parameter to `java_opts`

Change JAVA_OPTS behavior for Keycloak

---

README.md
lib/puppet/provider/keycloak_api.rb
lib/puppet/type/keycloak_api.rb
manifests/config.pp
manifests/datasource/mysql.pp
manifests/datasource/oracle.pp
manifests/datasource/postgresql.pp
manifests/init.pp
manifests/install.pp
spec/acceptance/99_keycloak_api_spec.rb

The default for `install_dir` changes from `/opt` to `/opt/keycloak-$version`.

Change how install_dir is defined, default behavior remains the same

---

.sync.yml
.travis.yml
README.md
manifests/init.pp
metadata.json
spec/classes/init_spec.rb
spec/spec_helper_acceptance_setup.rb

**Important** If you wish to remain on non-default version, you must set the `version` parameter for `keycloak` class.

Change default Keycloak version to 8.0.1

---

lib/puppet/provider/keycloak_client/kcadm.rb
lib/puppet/type/keycloak_client.rb

This also fixes handling of attributes that have dots in their names, which
means most of them, excluding "login_theme". Here is a truncated example:
```
"attributes" : {
"saml.assertion.signature" : "false",
"access.token.lifespan" : "600",
"saml.multivalued.roles" : "false",
"saml.force.post.binding" : "false",
"saml.encrypt" : "false",
"login_theme" : "keycloak",
"saml.server.signature" : "false",
"saml.server.signature.keyinfo.ext" : "false",
--- snip ---
```
Without the dot_key fix in the "flush" method Puppet added and tried to manage _access_token_lifespan_ instead of _access.token.lifespan_.

Add support for access.token.lifespan client attribute

---

lib/puppet/provider/keycloak_client_protocol_mapper/kcadm.rb
lib/puppet/provider/keycloak_protocol_mapper/kcadm.rb
lib/puppet/type/keycloak_client_protocol_mapper.rb
lib/puppet/type/keycloak_protocol_mapper.rb
spec/acceptance/6_protocol_mapper_spec.rb
spec/acceptance/7_client_protocol_mapper_spec.rb
spec/unit/puppet/type/keycloak_client_protocol_mapper_spec.rb
spec/unit/puppet/type/keycloak_protocol_mapper_spec.rb

Allow keycloak_protocol_mapper and keycloak_client_protocol_mapper to have 'oidc-group-membership-mapper' for 'type'
Add full_path property to keycloak_protocol_mapper and keycloak_client_protocol_mapper

Support oidc-group-membership-mapper protocol mapper type

---

lib/puppet/type/keycloak_api.rb

This PR sets a default value for the `install_dir` in the `keycloak_api` type. 
When this default is not set, and there is no `install_dir` given like
```puppet
keycloak_api { 'keycloak':
install_dir => '/opt/keycloak',
realm       => 'master',
user        => $master_realm_user,
password    => $master_realm_password
}
```
a Puppet run fails with `Failed to apply catalog: no implicit conversion of nil into String`
Just setting the `install_dir` makes the error go away, but I think it makes sense to set a default, as this is the general default installation directory for keycloak.

type/keycloak_api: Set install_dir default on /opt/keycloak

---

lib/puppet/provider/keycloak_client/kcadm.rb
lib/puppet/type/keycloak_client.rb
spec/acceptance/5_client_spec.rb

While this is a seemingly trivial change, there are issues in the Keycloak API (at least in 6.x) that makes the user-experience less than optimal and require discussion.
First of all _"authorizationServicesEnabled": true_ depends on _"serviceAccountsEnabled": true_. Trying to set the latter to true while former is false will give an 500 Internal Server Error. We may be able to prevent such transitions with proper validation.
Secondly  _"authorizationServicesEnabled"_ from _true_ to _false_ works. But changing it back from _false_ to _true_ does not - you get 500 Internal server error and this in the logs:
```
2020-03-11 09:44:30,247 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (default task-26) Uncaught server error: java.lang.RuntimeException: Client does not have a service …
```

Allow enabling/disabling client authorization services

---

manifests/init.pp

manage_datasource supports postgresql since https://github.com/treydock/puppet-module-keycloak/commit/02803c314a1da4a4a15eba1fe1c4d6a1f781389f

Remove outdated line in class documentation

---

README.md
manifests/init.pp
spec/acceptance/1_class_spec.rb
templates/config.cli.erb

Closes https://github.com/treydock/puppet-module-keycloak/issues/138

Add support for JGroups JDBC_PING mode in clustered mode

---

.fixtures.yml
manifests/datasource/postgresql.pp
metadata.json

The function `postgresql_password` was recently deprecated in puppetlabs-postgresql: https://github.com/puppetlabs/puppetlabs-postgresql/blob/master/REFERENCE.md#postgresql_password, causing a deprecation warning.
Suggested replacement: `postgresql::postgresql_password`

Update usage of deprecated function postgresql_password

---

manifests/config.pp

**Description**
This change explicitly specifies what user to use with the admin generation script,
so the keycloak would have no issues accessing generated keycloak-add-user.json.
**Background**
The add-user-keycloak generates keycloak-add-user.json belonging to a user that runs the script.
This means if puppet and keycloak services belong to different users,
without this change there was no guarantee that keycloak could access to this file after creation.

Explicitly specifies what user to use with the admin generation script

---

README.md
lib/puppet/provider/keycloak_required_action/kcadm.rb
lib/puppet/type/keycloak_required_action.rb
spec/acceptance/10_required_action_spec.rb
spec/fixtures/unit/puppet/provider/keycloak_required_action/kcadm/get-master.out
spec/fixtures/unit/puppet/provider/keycloak_required_action/kcadm/get-test.out
spec/fixtures/unit/puppet/provider/keycloak_required_action/kcadm/get-unregistered-required-actions-master.out
spec/fixtures/unit/puppet/provider/keycloak_required_action/kcadm/get-unregistered-required-actions-test.out
spec/unit/puppet/provider/keycloak_required_action/kcadm_spec.rb
spec/unit/puppet/type/keycloak_required_action_spec.rb

**Description**
Required actions are actions a user must perform during the authentication process. A user will not be able to complete the authentication process until these actions are complete. For instance, change a one-time password, accept T&C, etc.
**Note**
I deliberately did not add auto requires as it complicates the deconfiguration process. I.e. if I specify `ensure => absent` for both required_action and realm and the former auto requires the latter, then the realm would be deleted first and the puppet run would fail on deleting actions because they're specific to a realm and the realm no longer exists.

Add support for required actions

---

REFERENCE.md
lib/puppet/type/keycloak_realm.rb
spec/acceptance/2_realm_spec.rb
spec/unit/puppet/type/keycloak_realm_spec.rb

Enable to set  `registrationAllowed` realm parameter value from puppet.

Add registration_allowed to keycloak_realm

---

REFERENCE.md
lib/puppet/type/keycloak_realm.rb
spec/acceptance/2_realm_spec.rb
spec/unit/puppet/type/keycloak_realm_spec.rb

That PR enables to set `resetPasswordAllowed` and `verifyEmail` options to a realm from Puppet.

Add more realm login related properties

---

REFERENCE.md
lib/puppet/provider/keycloak_client/kcadm.rb
lib/puppet/provider/keycloak_realm/kcadm.rb
lib/puppet/type/keycloak_client.rb
lib/puppet/type/keycloak_realm.rb
spec/acceptance/2_realm_spec.rb
spec/acceptance/5_client_spec.rb
spec/unit/puppet/provider/keycloak_client/kcadm_spec.rb
spec/unit/puppet/provider/keycloak_realm/kcadm_spec.rb
spec/unit/puppet/type/keycloak_client_spec.rb
spec/unit/puppet/type/keycloak_realm_spec.rb

That PR enables to create/delete [roles](https://www.keycloak.org/docs/6.0/server_admin/#roles) at realm and client level.
Only simple (non composite) roles are considered.
Composite roles management could be added later by adding a new `keycloak_composite_role` type
setting the mapping between the new composite role and a list of other existing roles.

Enable roles management at realm and client level

---

vagrant-common.sh

Without it provisioning fails with missing module error.

Vagrant: install puppetlabs-concat during provisioning

---

README.md
manifests/freeipa_ldap_mappers.pp
spec/acceptance/3_ldap_spec.rb
spec/defines/freeipa_ldap_mappers_spec.rb

The mappings are well-known, so there's no reason for all FreeIPA users to set
them up separately.

Add convenience define for setting up FreeIPA LDAP mappers

---

lib/puppet/type/keycloak_ldap_user_provider.rb

The `IntegerProperty` is currently not explicitly required in the keycloak_ldap_user_provider which relies on that class. This does not cause issues most of the time as long as other classes that use `IntegerProperty` are loaded first. But under certain conditions like spec tests, the missing require causes failures like that:
```
error during compilation: Evaluation Error: Error while evaluating a Resource Statement, Could not autoload puppet/type/keycloak_ldap_user_provider: uninitialized constant PuppetX::Keycloak::IntegerProperty
Did you mean?  Interrupt (file: /.../provider/ldap.pp, line: 65, column: 5) on node laptop-esoynov.localdomain
```
I've added the explicit `require_relative` as it's done in other classes to fix the issue.

Fix missing IntegerProperty when keycloak_ldap_user_provider

---

vagrant-common.sh

Provisioning (ad hoc) Keycloak test instances that use postgresql fails without
this module.
Signed-off-by: Samuli Seppänen <samuli.seppanen@puppeteers.net>

Vagrant: install puppetlabs-postgresql

---

templates/config.cli/01-https-proxy.epp

This fixes the problem of using wrong address for socket-binding-groups in 01-https-proxy.epp caused by misuse of prefixes. This only affected domain mode, but was also wrong, albeit working for standalone mode. 
Signed-off-by: Kibahop <petri.lammi@puppeteers.net>

Remove prefixes from socket-binding-groups

---

REFERENCE.md
lib/puppet/type/keycloak_realm.rb
spec/acceptance/2_realm_spec.rb
spec/unit/puppet/type/keycloak_realm_spec.rb

Add support of :
- `accessCodeLifespanLogin`
- `actionTokenGeneratedByAdminLifespan`
- `actionTokenGeneratedByUserLifespan`
- `offlineSessionIdleTimeout`
- `offlineSessionMaxLifespan`
- `offlineSessionMaxLifespanEnabled`
Tested on Keycloak 11

Add extra configurations to keycloak realm

---

manifests/config.pp

In newest Keycloaks (>10), the stock host-master.xml does not include the native interface definition in management-interfaces. Fix assign-management-interfaces-master augeas resource.

Fix assigning management interfaces to logical interfaces in domain mode

---

vagrant-common.sh

On `vagrant up` provisioning would cause installed puppet modules to be in an incorect state:
/etc/puppetlabs/code/environments/production/modules
└─┬ treydock-keycloak (v7.7.0)
├── puppetlabs-stdlib (v8.0.0)  invalid
├── puppetlabs-mysql (v12.0.1)  invalid
├─┬ puppetlabs-postgresql (v7.4.1)
│ ├── puppetlabs-apt (v8.2.0)
│ └── puppetlabs-concat (v7.1.1)
├── puppetlabs-java (v1.3.0)  invalid
├── puppetlabs-java_ks (v4.2.0)
├── puppetlabs-augeas_core (v1.1.2)
├── puppetlabs-yumrepo_core (v1.0.7)
├── puppet-archive (v6.0.1)  invalid
└── camptocamp-systemd (v0.4.0)
This would cause keycloak to not be loaded properly

Fix invalid module dependency versions

---

Vagrantfile

Provisioning failed when trying to apply kernel-devel package and mounting /vagrant would break
```
--- snip ---
No package kernel-devel-3.10.0-1127.el7.x86_64 available.
Error: Nothing to do
Unmounting Virtualbox Guest Additions ISO from: /mnt
umount: /mnt: not mounted
--- snip ---
Vagrant assumes that this means the command failed!
umount /mnt
Stdout from the command:
Stderr from the command:
umount: /mnt: not mounted
```
After the initial fail, have to run `vagrant up keycloak` once again which would cause the keycloak module to error due to /vagrant not being mounted.

Fix centos/7 in Vagrant failing

---

manifests/init.pp

Fixes `keycloak_conn_validator` when `service_bind_address` is set to different value then `0.0.0.0` or `127.0.0.1`.  [fixes #215]

set keycloak_server in keycloak_conn_validator from 'localhost' to $service_bind_address

---

manifests/config.pp

When using my own packages, IMVHO it makes more sense to use `/opt/keycloak` instead of `/opt/keycloak-$version`. So I need to set `$keycloak::install_dir` to `/opt/keycloak`, but this conflicts with the symlink in `manifests/config.pp`, so this PR fixes that.

Fix issues with install_base /opt/keycloak

---

lib/puppet/provider/keycloak_client/kcadm.rb
spec/acceptance/5_client_spec.rb

Disabling authorization services for a client results, by design, removal of
all the authorization data for that client. Before this commit any property
changes (e.g. changing root_url) to a keycloak_client would generate a payload
that did not have authorizationServicesEnabled included. Keycloak interpreted
such a payload as "disable authorization services for the client", which in
turn resulted in unintentional destruction of the client's authorization data.
This commit fixes that behavior and adds tests to prevent future regressions.

Fix authorization services data corruption on unrelated client changes

---

README.md
lib/puppet/provider/keycloak_api.rb
lib/puppet/provider/keycloak_role_mapping/kcadm.rb
lib/puppet/type/keycloak_role_mapping.rb
spec/acceptance/11_role_mapping_spec.rb
spec/acceptance/get_role_mappings.rb
spec/unit/puppet/provider/keycloak_role_mapping/kcadm_spec.rb
spec/unit/puppet/type/keycloak_role_mapping_spec.rb

This is simplified version of the earlier PR (https://github.com/treydock/puppet-module-keycloak/pull/175). All it does is add realm role mapping support for users and groups.

Realm role mapping support

---

manifests/config.pp

According to official documentation, profile.properties must be placed under:
- standalone/configuration/profile.properties for standalone mode
- or domain/servers/server-one/configuration/profile.properties for server-one in domain mode.

fix profile.properties file path in domain mode

---

REFERENCE.md
manifests/db/mysql.pp
manifests/init.pp

Rel https://github.com/puppetlabs/puppetlabs-mysql/issues/1507
Provide a `db_collate` param mimicking current's `db_charset`

Add db_collate param

---

REFERENCE.md
lib/puppet/type/keycloak_ldap_user_provider.rb
spec/unit/puppet/type/keycloak_ldap_user_provider_spec.rb

Dear maintainer,
It allows to configure the parameters inside the "Kerberos integration" sub menu, for User federations.
the `useKerberosForPasswordAuthentication`, already exist, so it adds:
- `allowKerberosAuthentication`
- `kerberosRealm`
- `keyTab`
- `serverPrincipal`

Allow to configure LDAP kerberos through the module

---

.github/workflows/ci.yaml
.sync.yml
lib/puppet/provider/keycloak_conn_validator/puppet_https.rb
lib/puppet/util/keycloak_validator.rb
metadata.json
spec/acceptance/1_class_spec.rb

Improve logging of connection validator

---

manifests/db/postgres.pp
manifests/init.pp

Add db_encoding parameter for postgres

---

README.md
manifests/config.pp
manifests/init.pp
manifests/partial_import.pp
manifests/resources.pp
spec/acceptance/2_realm_spec.rb
spec/defines/partial_import_spec.rb
spec/fixtures/partial-import.json
spec/spec_helper_acceptance_setup.rb

Add keycloak::partial_import resource

---

Gemfile
lib/puppet/type/keycloak_client.rb
lib/puppet/type/keycloak_client_protocol_mapper.rb
lib/puppet/type/keycloak_flow.rb
lib/puppet/type/keycloak_flow_execution.rb
lib/puppet/type/keycloak_identity_provider.rb
lib/puppet/type/keycloak_ldap_mapper.rb
lib/puppet/type/keycloak_protocol_mapper.rb
lib/puppet_x/keycloak/type.rb
manifests/init.pp
metadata.json
spec/classes/init_spec.rb
spec/defines/freeipa_ldap_mappers_spec.rb
spec/defines/freeipa_user_provider_spec.rb
spec/defines/partial_import_spec.rb
spec/defines/spi_deployment_spec.rb

Do not purge truststore.jks by default

---

REFERENCE.md
manifests/init.pp

For servers without direct internet access it's usefull to use an absolute file path instead of a download url.

allow absolute path for package_url parameter

---

types/configs.pp

fixes on Puppet 8.6.0:
Server Error: The key '["log-level"]' is declared more than once (file: /etc/puppetlabs/code/environments/production/modules/keycloak/types/configs.pp, line: 69, column: 27)

Bugfix: remove double declaration of "log-level"

---

lib/puppet/provider/keycloak_ldap_user_provider/kcadm.rb
spec/unit/puppet/provider/keycloak_ldap_user_provider/kcadm_spec.rb

This change will fix #306 as it will try to retrieve the uuid of the given realm first and pass it as `parentId`.
It is a quiet similar solution like in https://github.com/treydock/puppet-module-keycloak/blob/master/lib/puppet/provider/keycloak_ldap_mapper/kcadm.rb#L127

Fix #306 - Retrieve parentId by realm name

---

lib/puppet/type/keycloak_realm.rb
spec/acceptance/2_realm_spec.rb
spec/unit/puppet/type/keycloak_realm_spec.rb

This PR implements all webauthn and bruteforce properties on a realm supported by at least Keycloak 22.0.0.
WebAuthn Extra Origins and passwordless WebAuthn properties are not yet supported as these were introduced in later Keycloak versions.

Implement realm otp, webauthn, webauthn passwordless and bruteforce properties

---

lib/puppet/type/keycloak_realm.rb
spec/acceptance/2_realm_spec.rb
spec/unit/puppet/type/keycloak_realm_spec.rb

A simple implementation of the password policy property on realms.
It would enable us to configure password policy on our keycloak installations. 
Is it a good enough implementation or would you like to have some kind of seperate properties which get then send as `passwordPolicy` property to keycloak api?
It's kind of strange implementation on keycloak side that they don't expose the options seperatly instead they use some string with `and` to combine rules.

Implement password policy property

---

.github/workflows/ci.yaml
.sync.yml
README.md
lib/puppet/type/keycloak_realm.rb
manifests/init.pp
spec/acceptance/2_realm_spec.rb
spec/classes/init_spec.rb
spec/defines/partial_import_spec.rb
spec/defines/spi_deployment_spec.rb
spec/spec_helper_acceptance_setup.rb
spec/unit/puppet/type/keycloak_realm_spec.rb

https://github.com/treydock/puppet-module-keycloak/pull/312 implements quiet a few properties on the realm resource.
The webauthn & webauthn passwordless extra origins property require at least KeyCloak 23.0.0 as it was added with that release.
This PR raises the minimum KeyCloak version used for acceptance testing and will add these properties.

Implement webauthn extra origins & Raise KeyCloak version to 24.0.5 in acceptance tests

---

README.md
lib/puppet/provider/keycloak_required_action/kcadm.rb
lib/puppet/type/keycloak_required_action.rb
spec/acceptance/10_required_action_spec.rb
spec/unit/puppet/provider/keycloak_required_action/kcadm_spec.rb
spec/unit/puppet/type/keycloak_required_action_spec.rb

This PR will adjust the keycloak_required_action resource that it no longer uses the `alias` metaparameter which leads to problems if you want to manage the same required action on multiple realms.
The github issue #320 shows the exact code and error. I tested serveral ways but the current version does not allow to manage the same required action on multiple realms.
Fixes #320

Adjust keycloak_required_action resource to not use metaparameter alias

---

REFERENCE.md
lib/puppet/provider/keycloak_client_scope/kcadm.rb
lib/puppet/type/keycloak_client_scope.rb
spec/unit/puppet/type/keycloak_client_scope_spec.rb

We have additional updates, please, consider merging.
In this PR we add include.in.token.scope attribute of client scope.
Thank you.
Regards,
Robert.

Client scope / Include in token scope attribute
